/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedVosProduitsRouteImport } from './routes/_authenticated/vos-produits'
import { Route as AuthenticatedRetraitRouteImport } from './routes/_authenticated/retrait'
import { Route as AuthenticatedRechargerRouteImport } from './routes/_authenticated/recharger'
import { Route as AuthenticatedPlansInvestissementRouteImport } from './routes/_authenticated/plans-investissement'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVosProduitsRoute =
  AuthenticatedVosProduitsRouteImport.update({
    id: '/_authenticated/vos-produits',
    path: '/vos-produits',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRetraitRoute = AuthenticatedRetraitRouteImport.update({
  id: '/_authenticated/retrait',
  path: '/retrait',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRechargerRoute = AuthenticatedRechargerRouteImport.update({
  id: '/_authenticated/recharger',
  path: '/recharger',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlansInvestissementRoute =
  AuthenticatedPlansInvestissementRouteImport.update({
    id: '/_authenticated/plans-investissement',
    path: '/plans-investissement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/_authenticated/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/_authenticated/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/_authenticated/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/plans-investissement': typeof AuthenticatedPlansInvestissementRoute
  '/recharger': typeof AuthenticatedRechargerRoute
  '/retrait': typeof AuthenticatedRetraitRoute
  '/vos-produits': typeof AuthenticatedVosProduitsRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/plans-investissement': typeof AuthenticatedPlansInvestissementRoute
  '/recharger': typeof AuthenticatedRechargerRoute
  '/retrait': typeof AuthenticatedRetraitRoute
  '/vos-produits': typeof AuthenticatedVosProduitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/plans-investissement': typeof AuthenticatedPlansInvestissementRoute
  '/_authenticated/recharger': typeof AuthenticatedRechargerRoute
  '/_authenticated/retrait': typeof AuthenticatedRetraitRoute
  '/_authenticated/vos-produits': typeof AuthenticatedVosProduitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/accueil'
    | '/equipe'
    | '/mon-compte'
    | '/plans-investissement'
    | '/recharger'
    | '/retrait'
    | '/vos-produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/accueil'
    | '/equipe'
    | '/mon-compte'
    | '/plans-investissement'
    | '/recharger'
    | '/retrait'
    | '/vos-produits'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/_authenticated/accueil'
    | '/_authenticated/equipe'
    | '/_authenticated/mon-compte'
    | '/_authenticated/plans-investissement'
    | '/_authenticated/recharger'
    | '/_authenticated/retrait'
    | '/_authenticated/vos-produits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedPlansInvestissementRoute: typeof AuthenticatedPlansInvestissementRoute
  AuthenticatedRechargerRoute: typeof AuthenticatedRechargerRoute
  AuthenticatedRetraitRoute: typeof AuthenticatedRetraitRoute
  AuthenticatedVosProduitsRoute: typeof AuthenticatedVosProduitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vos-produits': {
      id: '/_authenticated/vos-produits'
      path: '/vos-produits'
      fullPath: '/vos-produits'
      preLoaderRoute: typeof AuthenticatedVosProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retrait': {
      id: '/_authenticated/retrait'
      path: '/retrait'
      fullPath: '/retrait'
      preLoaderRoute: typeof AuthenticatedRetraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recharger': {
      id: '/_authenticated/recharger'
      path: '/recharger'
      fullPath: '/recharger'
      preLoaderRoute: typeof AuthenticatedRechargerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plans-investissement': {
      id: '/_authenticated/plans-investissement'
      path: '/plans-investissement'
      fullPath: '/plans-investissement'
      preLoaderRoute: typeof AuthenticatedPlansInvestissementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedPlansInvestissementRoute: AuthenticatedPlansInvestissementRoute,
  AuthenticatedRechargerRoute: AuthenticatedRechargerRoute,
  AuthenticatedRetraitRoute: AuthenticatedRetraitRoute,
  AuthenticatedVosProduitsRoute: AuthenticatedVosProduitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
