/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VosProduitsRouteImport } from './routes/vos-produits'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RetraitRouteImport } from './routes/retrait'
import { Route as RechargerRouteImport } from './routes/recharger'
import { Route as PlansInvestissementRouteImport } from './routes/plans-investissement'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const VosProduitsRoute = VosProduitsRouteImport.update({
  id: '/vos-produits',
  path: '/vos-produits',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RetraitRoute = RetraitRouteImport.update({
  id: '/retrait',
  path: '/retrait',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargerRoute = RechargerRouteImport.update({
  id: '/recharger',
  path: '/recharger',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansInvestissementRoute = PlansInvestissementRouteImport.update({
  id: '/plans-investissement',
  path: '/plans-investissement',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipe': typeof EquipeRoute
  '/mon-compte': typeof MonCompteRoute
  '/plans-investissement': typeof PlansInvestissementRoute
  '/recharger': typeof RechargerRoute
  '/retrait': typeof RetraitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vos-produits': typeof VosProduitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipe': typeof EquipeRoute
  '/mon-compte': typeof MonCompteRoute
  '/plans-investissement': typeof PlansInvestissementRoute
  '/recharger': typeof RechargerRoute
  '/retrait': typeof RetraitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vos-produits': typeof VosProduitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipe': typeof EquipeRoute
  '/mon-compte': typeof MonCompteRoute
  '/plans-investissement': typeof PlansInvestissementRoute
  '/recharger': typeof RechargerRoute
  '/retrait': typeof RetraitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vos-produits': typeof VosProduitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/equipe'
    | '/mon-compte'
    | '/plans-investissement'
    | '/recharger'
    | '/retrait'
    | '/sitemap.xml'
    | '/vos-produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/equipe'
    | '/mon-compte'
    | '/plans-investissement'
    | '/recharger'
    | '/retrait'
    | '/sitemap.xml'
    | '/vos-produits'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/equipe'
    | '/mon-compte'
    | '/plans-investissement'
    | '/recharger'
    | '/retrait'
    | '/sitemap.xml'
    | '/vos-produits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EquipeRoute: typeof EquipeRoute
  MonCompteRoute: typeof MonCompteRoute
  PlansInvestissementRoute: typeof PlansInvestissementRoute
  RechargerRoute: typeof RechargerRoute
  RetraitRoute: typeof RetraitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VosProduitsRoute: typeof VosProduitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vos-produits': {
      id: '/vos-produits'
      path: '/vos-produits'
      fullPath: '/vos-produits'
      preLoaderRoute: typeof VosProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrait': {
      id: '/retrait'
      path: '/retrait'
      fullPath: '/retrait'
      preLoaderRoute: typeof RetraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharger': {
      id: '/recharger'
      path: '/recharger'
      fullPath: '/recharger'
      preLoaderRoute: typeof RechargerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans-investissement': {
      id: '/plans-investissement'
      path: '/plans-investissement'
      fullPath: '/plans-investissement'
      preLoaderRoute: typeof PlansInvestissementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EquipeRoute: EquipeRoute,
  MonCompteRoute: MonCompteRoute,
  PlansInvestissementRoute: PlansInvestissementRoute,
  RechargerRoute: RechargerRoute,
  RetraitRoute: RetraitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VosProduitsRoute: VosProduitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
